/*
 Navicat Premium Dump SQL

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 90500 (9.5.0)
 Source Host           : localhost:3306
 Source Schema         : taihe

 Target Server Type    : MySQL
 Target Server Version : 90500 (9.5.0)
 File Encoding         : 65001

 Date: 04/12/2025 08:15:32
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for wu_xing_attribute
-- ----------------------------
DROP TABLE IF EXISTS `wu_xing_attribute`;
CREATE TABLE `wu_xing_attribute`  (
  `id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `element_key` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '五行元素键名',
  `element_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '五行代码',
  `element_category` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '元素分类:basic五行,extended扩展,combined组合',
  `element_name_en` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '英文名称',
  `element_name_zh` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '中文名称',
  `element_name_ar` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '阿拉伯语名称',
  `symbol_character` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '象征字符',
  `symbol_color` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '象征颜色代码',
  `symbol_color_gradient` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '渐变色系',
  `symbol_direction` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征方位',
  `symbol_season` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征季节',
  `symbol_time` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征时辰',
  `symbol_planet` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征行星',
  `symbol_weather` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征气候',
  `symbol_landform` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征地貌',
  `symbol_animal` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征动物',
  `symbol_plant` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征植物',
  `symbol_organ` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征脏腑',
  `symbol_sense` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征感官',
  `symbol_tissue` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征组织',
  `symbol_emotion` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征情绪',
  `symbol_sound` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征声音',
  `symbol_taste` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征味道',
  `symbol_virtue` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征品德',
  `symbol_career` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征职业',
  `symbol_number` tinyint NULL DEFAULT NULL COMMENT '象征数字',
  `symbol_music` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征音律',
  `philosophy_meaning_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文哲学本义',
  `philosophy_meaning_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文哲学本义',
  `cosmology_meaning_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文宇宙观含义',
  `cosmology_meaning_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文宇宙观含义',
  `life_philosophy_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文生命哲学',
  `life_philosophy_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文生命哲学',
  `change_principle_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文变化法则',
  `change_principle_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文变化法则',
  `cultural_symbolism_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文文化象征',
  `cultural_symbolism_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文文化象征',
  `mythological_association_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文神话关联',
  `mythological_association_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文神话关联',
  `historical_reference_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文历史典故',
  `historical_reference_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文历史典故',
  `artistic_expression_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文艺术表现',
  `artistic_expression_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文艺术表现',
  `energy_essence_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文能量本质',
  `energy_essence_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文能量本质',
  `energy_manifestation_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文能量显现',
  `energy_manifestation_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文能量显现',
  `spiritual_meaning_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文灵性意义',
  `spiritual_meaning_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文灵性意义',
  `personality_archetype_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文人格原型',
  `personality_archetype_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文人格原型',
  `life_guidance_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文人生指引',
  `life_guidance_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文人生指引',
  `healing_property_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文疗愈属性',
  `healing_property_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文疗愈属性',
  `generates_element` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '相生元素',
  `generated_by_element` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '被生元素',
  `restrains_element` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '相克元素',
  `restrained_by_element` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '被克元素',
  `relationship_meaning_zh` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '中文关系意义',
  `relationship_meaning_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '英文关系意义',
  `symbol_icon_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征图标URL',
  `philosophy_image_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '哲学图解URL',
  `energy_flow_image_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '能量流动图URL',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序值',
  `element_tier` tinyint NOT NULL DEFAULT 1 COMMENT '元素层级',
  `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `symbol_icon_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '象征图标ID（用于UI展示的小图标）',
  `philosophy_image_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '哲学原理图ID（五行相生相克关系图）',
  `energy_flow_image_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '能量流动图ID（能量流动示意图）',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '五行哲学文化属性表(完整版)' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of wu_xing_attribute
-- ----------------------------
INSERT INTO `wu_xing_attribute` VALUES ('WX001', 'metal', 'JIN', 'basic', 'Metal', '金', 'معدن', '金', '#FFFFFF', 'linear-gradient(135deg, #FFFFFF, #E0E0E0)', '西', '秋', '申酉', '金星', '干燥', '山脉', '虎', '菊花', '肺', '鼻', '皮毛', '悲', '商', '辛', '义', '金融', 9, '商音', '金的哲学本义是变革、收敛、肃杀，代表从混沌到有序的转化过程。', 'The philosophical essence of Metal is transformation, convergence, and solemnity, representing the process from chaos to order.', '在宇宙观中，金代表西方的收敛能量，秋季的肃杀之气，万物成熟的终结阶段。', 'In cosmology, Metal represents the收敛 energy of the west, the solemn atmosphere of autumn, and the final stage of万物成熟.', '生命哲学上，金教导我们学会放下、收敛锋芒，在变革中找到新的秩序。', 'In life philosophy, Metal teaches us to let go,收敛锋芒, and find new order in transformation.', '金的変化法则是\"从革\"，即变革更新，破旧立新，化繁为简。', 'The change principle of Metal is \"从革\" - transformation and renewal, breaking the old and establishing the new, simplifying complexity.', '金在文化中象征财富、权力、精密、纪律，代表西方白虎、秋季收获。', 'Culturally, Metal symbolizes wealth, power, precision, discipline, representing the White Tiger of the West and autumn harvest.', '神话中金与太白金星、西方天帝少昊关联，代表金属冶炼之神。', 'Mythologically, Metal is associated with Venus and the Western Emperor Shaohao, representing the god of metal smelting.', '历史典故有\"金石为开\"、\"点石成金\"，象征坚定不移和转化力量。', 'Historical references include \"金石为开\" and \"点石成金\", symbolizing steadfastness and transformative power.', '艺术表现上，金体现在青铜器、金银器、精密机械、几何图案中。', 'Artistically, Metal is manifested in bronze ware, gold and silverware, precision machinery, and geometric patterns.', '金的能量本质是收敛、凝聚、精炼，具有筛选和净化的特性。', 'The energy essence of Metal is收敛, condensation, and refinement, with characteristics of screening and purification.', '能量显现为精确的结构、清晰的边界、冷静的判断和高效的执行。', 'Energy manifestation appears as precise structure, clear boundaries,冷静 judgment, and efficient execution.', '金的灵性意义在于帮助灵魂学会释放、净化、精炼，达到更高纯度。', 'The spiritual meaning of Metal is to help the soul learn to release, purify, and refine to achieve higher purity.', '金的人格原型是审判者、精炼师、金融家，具有冷静、客观、精确的特质。', 'The personality archetype of Metal is the judge, refiner, financier, with calm, objective, and precise qualities.', '人生指引：学会适时收敛，去芜存菁，在变革中保持核心价值。', 'Life guidance: Learn to收敛适时, eliminate the false and retain the true, maintain core values in transformation.', '疗愈属性：帮助呼吸系统疾病，增强免疫力，净化负面能量。', 'Healing properties: Help with respiratory diseases, enhance immunity, purify negative energy.', '水', '土', '木', '火', '金生水，金克木；金被土生，被火克。代表变革中的生成与制约关系。', 'Metal generates Water, Metal restrains Wood; Metal is generated by Earth, restrained by Fire. Represents the relationship of generation and restraint in transformation.', '/api/files/PRODUCTEMO/2025/12/03/20251203134353350799.png', '/api/files/PRODUCTEMO/2025/12/03/20251203134353425841.jpg', '/api/files/PRODUCTEMO/2025/12/03/20251203134353428501.png', 100, 1, 1, '2025-11-19 08:35:43', '2025-12-03 13:43:53', '386754395151396864', '386754395461775360', '386754395482746880');
INSERT INTO `wu_xing_attribute` VALUES ('WX002', 'wood', 'MU', 'basic', 'Wood', '木', 'خشب', '木', '#4CAF50', 'linear-gradient(135deg, #4CAF50, #81C784)', '东', '春', '寅卯', '木星', '温和', '森林', '龙', '松树', '肝', '目', '筋', '怒', '角', '酸', '仁', '教育', 8, '角音', '木的哲学本义是生长、扩展、柔韧，代表生命力的萌发和扩张。', 'The philosophical essence of Wood is growth, expansion, and flexibility, representing the germination and expansion of vitality.', '在宇宙观中，木代表东方的生发能量，春季的萌动之气，万物开始的初始阶段。', 'In cosmology, Wood represents the生发 energy of the east, the sprouting atmosphere of spring, and the initial stage of万物开始.', '生命哲学上，木教导我们保持柔韧、积极成长，在变化中适应和发展。', 'In life philosophy, Wood teaches us to remain flexible, grow positively, and adapt and develop in change.', '木的変化法则是\"曲直\"，即能屈能伸，柔韧适应，生长扩展。', 'The change principle of Wood is \"曲直\" - able to bend and stretch, flexible adaptation, growth and expansion.', '木在文化中象征成长、教育、仁慈、活力，代表东方青龙、春季生机。', 'Culturally, Wood symbolizes growth, education, benevolence, vitality, representing the Green Dragon of the East and spring vitality.', '神话中木与青帝伏羲、春神句芒关联，代表生命和智慧之神。', 'Mythologically, Wood is associated with the Green Emperor Fuxi and the Spring God Goumang, representing the god of life and wisdom.', '历史典故有\"草木皆兵\"、\"木秀于林\"，象征生机勃勃和突出优秀。', 'Historical references include \"草木皆兵\" and \"木秀于林\", symbolizing vitality and outstanding excellence.', '艺术表现上，木体现在园林艺术、木雕、书法、水墨画中的线条美。', 'Artistically, Wood is manifested in garden art, wood carving, calligraphy, and the beauty of lines in ink painting.', '木的能量本质是生发、扩展、柔韧，具有生长和适应的特性。', 'The energy essence of Wood is生发, expansion, and flexibility, with characteristics of growth and adaptation.', '能量显现为向上的生长力、向外扩展、柔韧适应和创造性表达。', 'Energy manifestation appears as upward growth force, outward expansion, flexible adaptation, and creative expression.', '木的灵性意义在于帮助灵魂学会成长、扩展、适应，实现生命潜能。', 'The spiritual meaning of Wood is to help the soul learn to grow, expand, adapt, and realize life potential.', '木的人格原型是教育家、创造者、探险家，具有仁慈、活力、创新的特质。', 'The personality archetype of Wood is the educator, creator, explorer, with benevolent, vibrant, and innovative qualities.', '人生指引：保持成长心态，柔韧适应变化，培养仁慈和创造力。', 'Life guidance: Maintain a growth mindset, flexibly adapt to changes, cultivate benevolence and creativity.', '疗愈属性：帮助肝脏疾病，缓解压力，促进新陈代谢，增强活力。', 'Healing properties: Help with liver diseases, relieve stress, promote metabolism, enhance vitality.', '火', '水', '土', '金', '木生火，木克土；木被水生，被金克。代表生长中的生成与制约关系。', 'Wood generates Fire, Wood restrains Earth; Wood is generated by Water, restrained by Metal. Represents the relationship of generation and restraint in growth.', '/api/files/PRODUCTEMO/2025/12/03/20251203134437792304.jpg', '/api/files/PRODUCTEMO/2025/12/03/20251203134437795033.png', '/api/files/PRODUCTEMO/2025/12/03/20251203134437798837.png', 200, 1, 1, '2025-11-19 08:35:43', '2025-12-03 13:44:37', '386754581546266624', '386754581563043840', '386754581575626752');
INSERT INTO `wu_xing_attribute` VALUES ('WX003', 'water', 'SHUI', 'basic', 'Water', '水', 'ماء', '水', '#2196F3', 'linear-gradient(135deg, #2196F3, #64B5F6)', '北', '冬', '亥子', '水星', '寒冷', '江河', '龟', '莲花', '肾', '耳', '骨', '恐', '羽', '咸', '智', '科研', 6, '羽音', '水的哲学本义是流动、适应、智慧，代表无形中的变化和深度。', 'The philosophical essence of Water is flow, adaptation, and wisdom, representing change in formlessness and depth.', '在宇宙观中，水代表北方的收藏能量，冬季的沉淀之气，万物归藏的深藏阶段。', 'In cosmology, Water represents the收藏 energy of the north, the沉淀 atmosphere of winter, and the deep storage stage of万物归藏.', '生命哲学上，水教导我们顺势而为，以柔克刚，在流动中找到智慧。', 'In life philosophy, Water teaches us to go with the flow, overcome hardness with softness, and find wisdom in流动.', '水的変化法则是\"润下\"，即滋润向下，渗透融合，以柔克刚。', 'The change principle of Water is \"润下\" - moisturizing downward,渗透 fusion, overcoming hardness with softness.', '水在文化中象征智慧、流动、适应、深度，代表北方玄武、冬季沉淀。', 'Culturally, Water symbolizes wisdom, flow, adaptation, depth, representing the Black Tortoise of the North and winter沉淀.', '神话中水与黑帝颛顼、冬神玄冥关联，代表智慧和深渊之神。', 'Mythologically, Water is associated with the Black Emperor Zhuanxu and the Winter God Xuanming, representing the god of wisdom and abyss.', '历史典故有\"水能载舟\"、\"上善若水\"，象征适应性和智慧力量。', 'Historical references include \"水能载舟\" and \"上善若水\", symbolizing adaptability and wisdom power.', '艺术表现上，水体现在流水曲线、水墨渲染、音乐流动感中。', 'Artistically, Water is manifested in flowing curves, ink wash rendering, and the sense of flow in music.', '水的能量本质是流动、渗透、融合，具有适应和净化的特性。', 'The energy essence of Water is flow,渗透, fusion, with characteristics of adaptation and purification.', '能量显现为向下的流动、渗透融合、适应变化和深度思考。', 'Energy manifestation appears as downward flow,渗透 fusion, adaptation to change, and deep thinking.', '水的灵性意义在于帮助灵魂学会流动、净化、深度连接，获得内在智慧。', 'The spiritual meaning of Water is to help the soul learn to flow, purify, connect deeply, and gain inner wisdom.', '水的人格原型是智者、科学家、哲学家，具有智慧、深度、适应的特质。', 'The personality archetype of Water is the wise person, scientist, philosopher, with wise, deep, and adaptive qualities.', '人生指引：学会顺势而为，保持流动和适应，培养深度智慧。', 'Life guidance: Learn to go with the flow, maintain流动 and adaptation, cultivate deep wisdom.', '疗愈属性：帮助肾脏疾病，净化身体，增强记忆力，平衡情绪。', 'Healing properties: Help with kidney diseases, purify the body, enhance memory, balance emotions.', '木', '金', '火', '土', '水生木，水克火；水被金生，被土克。代表流动中的生成与制约关系。', 'Water generates Wood, Water restrains Fire; Water is generated by Metal, restrained by Earth. Represents the relationship of generation and restraint in flow.', '/api/files/PRODUCTEMO/2025/12/03/20251203134844385700.jpg', '/api/files/PRODUCTEMO/2025/12/03/20251203134844388447.jpg', '/api/files/PRODUCTEMO/2025/12/03/20251203134844392931.png', 300, 1, 1, '2025-11-19 08:35:43', '2025-12-03 13:48:44', '386755615836467200', '386755615849050112', '386755615865827328');
INSERT INTO `wu_xing_attribute` VALUES ('WX004', 'fire', 'HUO', 'basic', 'Fire', '火', 'نار', '火', '#F44336', 'linear-gradient(135deg, #F44336, #E57373)', '南', '夏', '巳午', '火星', '炎热', '火山', '凤', '牡丹', '心', '舌', '脉', '喜', '徵', '苦', '礼', '艺术', 7, '徵音', '火的哲学本义是热情、转化、光明，代表能量释放和意识觉醒。', 'The philosophical essence of Fire is passion, transformation, and light, representing energy release and consciousness awakening.', '在宇宙观中，火代表南方的炎上能量，夏季的旺盛之气，万物繁茂的鼎盛阶段。', 'In cosmology, Fire represents the炎上 energy of the south, the旺盛 atmosphere of summer, and the peak stage of万物繁茂.', '生命哲学上，火教导我们热情投入，转化提升，在光明中觉醒意识。', 'In life philosophy, Fire teaches us to engage passionately, transform and elevate, and awaken consciousness in light.', '火的変化法则是\"炎上\"，即向上燃烧，光明普照，转化提升。', 'The change principle of Fire is \"炎上\" - upward burning, illuminating widely, transformation and elevation.', '火在文化中象征热情、光明、礼仪、艺术，代表南方朱雀、夏季繁荣。', 'Culturally, Fire symbolizes passion, light, etiquette, art, representing the Vermilion Bird of the South and summer prosperity.', '神话中火与赤帝炎帝、夏神祝融关联，代表文明和光明之神。', 'Mythologically, Fire is associated with the Red Emperor Yandi and the Summer God Zhurong, representing the god of civilization and light.', '历史典故有\"如火如荼\"、\"星火燎原\"，象征热情旺盛和微小起势。', 'Historical references include \"如火如荼\" and \"星火燎原\", symbolizing passionate旺盛 and small beginnings.', '艺术表现上，火体现在热烈色彩、动态线条、激情音乐、戏剧表演中。', 'Artistically, Fire is manifested in passionate colors, dynamic lines,激情 music, and theatrical performances.', '火的能量本质是燃烧、转化、照亮，具有热情和觉醒的特性。', 'The energy essence of Fire is burning, transformation, illumination, with characteristics of passion and awakening.', '能量显现为向上的燃烧、热情表达、意识觉醒和创造性转化。', 'Energy manifestation appears as upward burning, passionate expression, consciousness awakening, and creative transformation.', '火的灵性意义在于帮助灵魂燃烧业力，转化提升，觉醒更高意识。', 'The spiritual meaning of Fire is to help the soul burn karma, transform and elevate, awaken higher consciousness.', '火的人格原型是艺术家、领袖、改革者，具有热情、光明、创造的特质。', 'The personality archetype of Fire is the artist, leader, reformer, with passionate, bright, and creative qualities.', '人生指引：保持热情投入，转化负面能量，用光明照亮自己和他人。', 'Life guidance: Maintain passionate engagement, transform negative energy, illuminate oneself and others with light.', '疗愈属性：帮助心脏疾病，提升能量，增强活力，改善循环。', 'Healing properties: Help with heart diseases,提升 energy, enhance vitality, improve circulation.', '土', '木', '金', '水', '火生土，火克金；火被木生，被水克。代表转化中的生成与制约关系。', 'Fire generates Earth, Fire restrains Metal; Fire is generated by Wood, restrained by Water. Represents the relationship of generation and restraint in transformation.', '/api/files/PRODUCTEMO/2025/12/03/20251203135247607787.jpg', '/api/files/PRODUCTEMO/2025/12/03/20251203135247611097.jpg', '/api/files/PRODUCTEMO/2025/12/03/20251203135247614232.png', 400, 1, 1, '2025-11-19 08:35:43', '2025-12-03 13:52:47', '386756635987668992', '386756636000251904', '386756636017029120');
INSERT INTO `wu_xing_attribute` VALUES ('WX005', 'earth', 'TU', 'basic', 'Earth', '土', 'تربة', '土', '#FFC107', 'linear-gradient(135deg, #FFC107, #FFD54F)', '中', '长夏', '辰戌丑未', '土星', '湿润', '平原', '牛', '稻谷', '脾', '口', '肉', '思', '宫', '甘', '信', '农业', 5, '宫音', '土的哲学本义是稳定、承载、转化，代表万物的基础和中心。', 'The philosophical essence of Earth is stability, bearing, and transformation, representing the foundation and center of all things.', '在宇宙观中，土代表中央的承载能量，季节交替的转化之气，万物孕育的中心阶段。', 'In cosmology, Earth represents the bearing energy of the center, the transformation atmosphere of seasonal changes, and the central stage of万物孕育.', '生命哲学上，土教导我们稳定根基，包容承载，在转化中孕育新生。', 'In life philosophy, Earth teaches us to stabilize the foundation,包容 bearing, and孕育 new life in transformation.', '土的変化法则是\"稼穑\"，即播种收获，承载化育，稳定中转化。', 'The change principle of Earth is \"稼穑\" - sowing and harvesting, bearing and nurturing, transformation in stability.', '土在文化中象征稳定、诚信、包容、孕育，代表中央黄龙、大地母亲。', 'Culturally, Earth symbolizes stability, integrity,包容,孕育, representing the Yellow Dragon of the Center and Mother Earth.', '神话中土与黄帝轩辕、土神后土关联，代表大地和孕育之神。', 'Mythologically, Earth is associated with the Yellow Emperor Xuanyuan and the Earth Goddess Houtu, representing the god of earth and孕育.', '历史典故有\"土生土长\"、\"积土成山\"，象征根基稳固和积累力量。', 'Historical references include \"土生土长\" and \"积土成山\", symbolizing solid foundation and accumulated strength.', '艺术表现上，土体现在厚重色彩、稳定构图、陶艺、大地艺术中。', 'Artistically, Earth is manifested in厚重 colors, stable composition, pottery, and land art.', '土的能量本质是稳定、承载、化育，具有包容和转化的特性。', 'The energy essence of Earth is stability, bearing, nurturing, with characteristics of包容 and transformation.', '能量显现为中心稳定、向下扎根、包容承载和孕育转化。', 'Energy manifestation appears as central stability, downward rooting,包容 bearing, and孕育 transformation.', '土的灵性意义在于帮助灵魂扎根大地，稳定核心，包容转化，孕育新生。', 'The spiritual meaning of Earth is to help the soul root in the earth, stabilize the core,包容 transform, and孕育 new life.', '土的人格原型是农夫、管理者、治愈者，具有稳定、诚信、包容的特质。', 'The personality archetype of Earth is the farmer, manager, healer, with stable, integrity,包容 qualities.', '人生指引：建立稳定根基，培养诚信品德，学会包容和孕育。', 'Life guidance: Establish a stable foundation, cultivate integrity, learn to包容 and孕育.', '疗愈属性：帮助脾胃疾病，增强消化，稳定情绪，促进营养吸收。', 'Healing properties: Help with spleen and stomach diseases, enhance digestion, stabilize emotions, promote nutrient absorption.', '金', '火', '水', '木', '土生金，土克水；土被火生，被木克。代表稳定中的生成与制约关系。', 'Earth generates Metal, Earth restrains Water; Earth is generated by Fire, restrained by Wood. Represents the relationship of generation and restraint in stability.', '/api/files/PRODUCTEMO/2025/12/03/20251203135633946891.jpg', '/api/files/PRODUCTEMO/2025/12/03/20251203135633950901.jpg', '/api/files/PRODUCTEMO/2025/12/03/20251203135633954693.png', 500, 1, 1, '2025-11-19 08:35:43', '2025-12-03 13:56:33', '386757585322242048', '386757585339019264', '386757585351602176');

SET FOREIGN_KEY_CHECKS = 1;
